In [1]:
import pandas as pd
import json
import glob
import os

In [2]:
path = r"D:\Rithu\Data Analytics\Portfolio Project\Spotify Extended Streaming History\data"

In [3]:
file_pattern = os.path.join("D:\Rithu\Data Analytics\Portfolio Project\Spotify Extended Streaming History\data","Streaming_History_Audio_*.json")
files = glob.glob(file_pattern)

In [4]:
dfs = []
for file in files:
    with open(file, 'r', encoding= 'utf-8') as f:
        data = pd.read_json(f)
        dfs.append(data)

In [5]:
df = pd.concat(dfs, ignore_index = True)

In [6]:
df.head()

,ts,platform,ms_played,conn_country,ip_addr,master_metadata_track_name,master_metadata_album_artist_name,master_metadata_album_album_name,spotify_track_uri,episode_name,...,audiobook_uri,audiobook_chapter_uri,audiobook_chapter_title,reason_start,reason_end,shuffle,skipped,offline,offline_timestamp,incognito_mode
0,2022-04-03T05:33:50Z,Windows 10 (10.0.22000; x64; AppX),208893,IN,117.204.120.138,Kabhi Khushi Kabhie Gham,Kris Bowers,Bridgerton Season Two,spotify:track:2uU4tNepmkbE5lyQ9d0zFZ,None,...,NaN,NaN,NaN,clickrow,trackdone,False,False,False,NaN,False
1,2022-04-03T05:35:47Z,Windows 10 (10.0.22000; x64; AppX),116170,IN,117.204.120.138,Diamonds,Hannah V,Bridgerton Season Two,spotify:track:6M4CKv0mfBDXKg8uIphjG0,None,...,NaN,NaN,NaN,trackdone,trackdone,False,False,False,NaN,False
2,2022-04-03T05:39:11Z,Windows 10 (10.0.22000; x64; AppX),203293,IN,117.204.120.138,Wildest Dreams,Duomo,Bridgerton (Covers from the Netflix Original S...,spotify:track:2fuiA0FQANMrcr2jXMc0nP,None,...,NaN,NaN,NaN,trackdone,trackdone,False,False,False,NaN,False
3,2022-04-03T05:40:22Z,Windows 10 (10.0.22000; x64; AppX),70063,IN,117.204.120.138,You Oughta Know,Duomo,Bridgerton Season Two,spotify:track:6eZXxcFFDaAcAli6LsEJdF,None,...,NaN,NaN,NaN,trackdone,endplay,False,False,False,NaN,False
4,2022-04-03T05:43:48Z,Windows 10 (10.0.22000; x64; AppX),206080,IN,117.204.120.138,Adrenaline,Solar,VINCENZO (Original Television Soundtrack) Pt. 3,spotify:track:6ZQmJVUuXk1Q27d8vkmgm8,None,...,NaN,NaN,NaN,clickrow,trackdone,False,False,False,NaN,False

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39568 entries, 0 to 39567
Data columns (total 23 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   ts                                 39568 non-null  object
 1   platform                           39568 non-null  object
 2   ms_played                          39568 non-null  int64
 3   conn_country                       39568 non-null  object
 4   ip_addr                            39568 non-null  object
 5   master_metadata_track_name         39511 non-null  object
 6   master_metadata_album_artist_name  39511 non-null  object
 7   master_metadata_album_album_name   39511 non-null  object
 8   spotify_track_uri                  39511 non-null  object
 9   episode_name                       57 non-null     object
 10  episode_show_name                  57 non-null     object
 11  spotify_episode_uri                57 non-null     object
 12  audiobook_title                    0 non-null      float64
 13  audiobook_uri                      0 non-null      float64
 14  audiobook_chapter_uri              0 non-null      float64
 15  audiobook_chapter_title            0 non-null      float64
 16  reason_start                       39568 non-null  object
 17  reason_end                         39568 non-null  object
 18  shuffle                            39568 non-null  bool
 19  skipped                            39568 non-null  bool
 20  offline                            39568 non-null  bool
 21  offline_timestamp                  35490 non-null  float64
 22  incognito_mode                     39568 non-null  bool
dtypes: bool(4), float64(5), int64(1), object(13)
memory usage: 5.9+ MB

In [8]:
df.describe()

,ms_played,audiobook_title,audiobook_uri,audiobook_chapter_uri,audiobook_chapter_title,offline_timestamp
count,3.956800e+04,0.0,0.0,0.0,0.0,3.549000e+04
mean,1.815185e+05,NaN,NaN,NaN,NaN,2.928126e+09
std,9.275297e+04,NaN,NaN,NaN,NaN,4.482314e+10
min,0.000000e+00,NaN,NaN,NaN,NaN,1.665758e+09
25%,1.377700e+05,NaN,NaN,NaN,NaN,1.686547e+09
50%,1.947940e+05,NaN,NaN,NaN,NaN,1.713030e+09
75%,2.304800e+05,NaN,NaN,NaN,NaN,1.742973e+09
max,2.962420e+06,NaN,NaN,NaN,NaN,1.664608e+12

In [9]:
df.isnull().sum()

ts                                       0
platform                                 0
ms_played                                0
conn_country                             0
ip_addr                                  0
master_metadata_track_name              57
master_metadata_album_artist_name       57
master_metadata_album_album_name        57
spotify_track_uri                       57
episode_name                         39511
episode_show_name                    39511
spotify_episode_uri                  39511
audiobook_title                      39568
audiobook_uri                        39568
audiobook_chapter_uri                39568
audiobook_chapter_title              39568
reason_start                             0
reason_end                               0
shuffle                                  0
skipped                                  0
offline                                  0
offline_timestamp                     4078
incognito_mode                           0
dtype: int64

In [10]:
cols_to_drop=['episode_name','episode_show_name','spotify_episode_uri','audiobook_title','audiobook_uri','audiobook_chapter_uri','audiobook_chapter_title','conn_country','ip_addr']
df = df.drop(columns=cols_to_drop)

In [11]:
df

,ts,platform,ms_played,master_metadata_track_name,master_metadata_album_artist_name,master_metadata_album_album_name,spotify_track_uri,reason_start,reason_end,shuffle,skipped,offline,offline_timestamp,incognito_mode
0,2022-04-03T05:33:50Z,Windows 10 (10.0.22000; x64; AppX),208893,Kabhi Khushi Kabhie Gham,Kris Bowers,Bridgerton Season Two,spotify:track:2uU4tNepmkbE5lyQ9d0zFZ,clickrow,trackdone,False,False,False,NaN,False
1,2022-04-03T05:35:47Z,Windows 10 (10.0.22000; x64; AppX),116170,Diamonds,Hannah V,Bridgerton Season Two,spotify:track:6M4CKv0mfBDXKg8uIphjG0,trackdone,trackdone,False,False,False,NaN,False
2,2022-04-03T05:39:11Z,Windows 10 (10.0.22000; x64; AppX),203293,Wildest Dreams,Duomo,Bridgerton (Covers from the Netflix Original S...,spotify:track:2fuiA0FQANMrcr2jXMc0nP,trackdone,trackdone,False,False,False,NaN,False
3,2022-04-03T05:40:22Z,Windows 10 (10.0.22000; x64; AppX),70063,You Oughta Know,Duomo,Bridgerton Season Two,spotify:track:6eZXxcFFDaAcAli6LsEJdF,trackdone,endplay,False,False,False,NaN,False
4,2022-04-03T05:43:48Z,Windows 10 (10.0.22000; x64; AppX),206080,Adrenaline,Solar,VINCENZO (Original Television Soundtrack) Pt. 3,spotify:track:6ZQmJVUuXk1Q27d8vkmgm8,clickrow,trackdone,False,False,False,NaN,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39563,2025-12-08T06:11:18Z,android,192507,Steal The Show,Lauv,Elemental,spotify:track:0SccFtYdj75y6lL2OW10Cf,fwdbtn,trackdone,True,False,False,1.765174e+09,False
39564,2025-12-08T06:15:44Z,android,265941,夏夜露天电影(Summer Night Open-Air Movie),白色海岸The White Coast,夏夜露天电影(Summer Night Open-Air Movie),spotify:track:2HqbxDaTBfMU3X1oraaKll,trackdone,trackdone,True,False,False,1.765174e+09,False
39565,2025-12-08T06:19:13Z,android,208307,Paparazzi,Lady Gaga,The Fame,spotify:track:02XnQdf7sipaKBBHixz3Zp,trackdone,trackdone,True,False,False,1.765175e+09,False
39566,2025-12-08T06:22:37Z,android,203352,Burning Up (Fire),BTS,The Most Beautiful Moment in Life: Young Forever,spotify:track:0aE3V0zgSD2YwkEHW42gxG,trackdone,trackdone,True,False,False,1.765175e+09,False
39567,2025-12-08T06:28:30Z,android,353253,Enchanted (Taylor's Version),Taylor Swift,Speak Now (Taylor's Version),spotify:track:3sW3oSbzsfecv9XoUdGs7h,trackdone,trackdone,True,False,False,1.765175e+09,False

In [12]:
df['ts']=pd.to_datetime(df['ts'])

In [13]:
df['year']=df['ts'].dt.year
df['month']=df['ts'].dt.month_name()
df['day_of_week']=df['ts'].dt.day_name()
df['hour']=df['ts'].dt.hour

In [14]:
df = df.rename(columns={
    'master_metadata_track_name':'track',
    'master_metadata_album_artist_name':'artist',
    'master_metadata_album_album_name':'album',
    'reason_start':'start_reason',
    'reason_end':'end_reason'
})

In [15]:
df

,ts,platform,ms_played,track,artist,album,spotify_track_uri,start_reason,end_reason,shuffle,skipped,offline,offline_timestamp,incognito_mode,year,month,day_of_week,hour
0,2022-04-03 05:33:50+00:00,Windows 10 (10.0.22000; x64; AppX),208893,Kabhi Khushi Kabhie Gham,Kris Bowers,Bridgerton Season Two,spotify:track:2uU4tNepmkbE5lyQ9d0zFZ,clickrow,trackdone,False,False,False,NaN,False,2022,April,Sunday,5
1,2022-04-03 05:35:47+00:00,Windows 10 (10.0.22000; x64; AppX),116170,Diamonds,Hannah V,Bridgerton Season Two,spotify:track:6M4CKv0mfBDXKg8uIphjG0,trackdone,trackdone,False,False,False,NaN,False,2022,April,Sunday,5
2,2022-04-03 05:39:11+00:00,Windows 10 (10.0.22000; x64; AppX),203293,Wildest Dreams,Duomo,Bridgerton (Covers from the Netflix Original S...,spotify:track:2fuiA0FQANMrcr2jXMc0nP,trackdone,trackdone,False,False,False,NaN,False,2022,April,Sunday,5
3,2022-04-03 05:40:22+00:00,Windows 10 (10.0.22000; x64; AppX),70063,You Oughta Know,Duomo,Bridgerton Season Two,spotify:track:6eZXxcFFDaAcAli6LsEJdF,trackdone,endplay,False,False,False,NaN,False,2022,April,Sunday,5
4,2022-04-03 05:43:48+00:00,Windows 10 (10.0.22000; x64; AppX),206080,Adrenaline,Solar,VINCENZO (Original Television Soundtrack) Pt. 3,spotify:track:6ZQmJVUuXk1Q27d8vkmgm8,clickrow,trackdone,False,False,False,NaN,False,2022,April,Sunday,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39563,2025-12-08 06:11:18+00:00,android,192507,Steal The Show,Lauv,Elemental,spotify:track:0SccFtYdj75y6lL2OW10Cf,fwdbtn,trackdone,True,False,False,1.765174e+09,False,2025,December,Monday,6
39564,2025-12-08 06:15:44+00:00,android,265941,夏夜露天电影(Summer Night Open-Air Movie),白色海岸The White Coast,夏夜露天电影(Summer Night Open-Air Movie),spotify:track:2HqbxDaTBfMU3X1oraaKll,trackdone,trackdone,True,False,False,1.765174e+09,False,2025,December,Monday,6
39565,2025-12-08 06:19:13+00:00,android,208307,Paparazzi,Lady Gaga,The Fame,spotify:track:02XnQdf7sipaKBBHixz3Zp,trackdone,trackdone,True,False,False,1.765175e+09,False,2025,December,Monday,6
39566,2025-12-08 06:22:37+00:00,android,203352,Burning Up (Fire),BTS,The Most Beautiful Moment in Life: Young Forever,spotify:track:0aE3V0zgSD2YwkEHW42gxG,trackdone,trackdone,True,False,False,1.765175e+09,False,2025,December,Monday,6
39567,2025-12-08 06:28:30+00:00,android,353253,Enchanted (Taylor's Version),Taylor Swift,Speak Now (Taylor's Version),spotify:track:3sW3oSbzsfecv9XoUdGs7h,trackdone,trackdone,True,False,False,1.765175e+09,False,2025,December,Monday,6

In [16]:
df.to_csv("spotify_master_data.csv", index=False)
print(f"Success! Processed {len(df)} rows. Saved to 'spotify_master_data.csv'.")

Success! Processed 39568 rows. Saved to 'spotify_master_data.csv'.

In [17]:
df['platform'] = df['platform'].str.lower()

def categorize_device(platform):
    if pd.isna(platform):
        return "Unknown"
    elif 'windows' in platform or 'osx' in platform or 'mac' in platform or 'desktop' in platform:
        return 'PC/Desktop'
    elif 'android' in platform or 'ios' in platform or 'iphone' in platform:
        return 'Mobile'
    elif 'amazon' in platform or 'bose' in platform or 'alexa' in platform or 'speaker' in platform:
        return 'Smart Speaker'
    else:
        return 'Other'

df['device_type'] = df['platform'].apply(categorize_device)

In [18]:
print(df['device_type'].value_counts())

device_type
Mobile           20969
PC/Desktop       16732
Other             1644
Smart Speaker      223
Name: count, dtype: int64

In [19]:
df = df[df['ms_played'] >= 30000]

In [20]:
df = df.dropna(subset=['track', 'album','artist'])

In [21]:
df

,ts,platform,ms_played,track,artist,album,spotify_track_uri,start_reason,end_reason,shuffle,skipped,offline,offline_timestamp,incognito_mode,year,month,day_of_week,hour,device_type
0,2022-04-03 05:33:50+00:00,windows 10 (10.0.22000; x64; appx),208893,Kabhi Khushi Kabhie Gham,Kris Bowers,Bridgerton Season Two,spotify:track:2uU4tNepmkbE5lyQ9d0zFZ,clickrow,trackdone,False,False,False,NaN,False,2022,April,Sunday,5,PC/Desktop
1,2022-04-03 05:35:47+00:00,windows 10 (10.0.22000; x64; appx),116170,Diamonds,Hannah V,Bridgerton Season Two,spotify:track:6M4CKv0mfBDXKg8uIphjG0,trackdone,trackdone,False,False,False,NaN,False,2022,April,Sunday,5,PC/Desktop
2,2022-04-03 05:39:11+00:00,windows 10 (10.0.22000; x64; appx),203293,Wildest Dreams,Duomo,Bridgerton (Covers from the Netflix Original S...,spotify:track:2fuiA0FQANMrcr2jXMc0nP,trackdone,trackdone,False,False,False,NaN,False,2022,April,Sunday,5,PC/Desktop
3,2022-04-03 05:40:22+00:00,windows 10 (10.0.22000; x64; appx),70063,You Oughta Know,Duomo,Bridgerton Season Two,spotify:track:6eZXxcFFDaAcAli6LsEJdF,trackdone,endplay,False,False,False,NaN,False,2022,April,Sunday,5,PC/Desktop
4,2022-04-03 05:43:48+00:00,windows 10 (10.0.22000; x64; appx),206080,Adrenaline,Solar,VINCENZO (Original Television Soundtrack) Pt. 3,spotify:track:6ZQmJVUuXk1Q27d8vkmgm8,clickrow,trackdone,False,False,False,NaN,False,2022,April,Sunday,5,PC/Desktop
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39563,2025-12-08 06:11:18+00:00,android,192507,Steal The Show,Lauv,Elemental,spotify:track:0SccFtYdj75y6lL2OW10Cf,fwdbtn,trackdone,True,False,False,1.765174e+09,False,2025,December,Monday,6,Mobile
39564,2025-12-08 06:15:44+00:00,android,265941,夏夜露天电影(Summer Night Open-Air Movie),白色海岸The White Coast,夏夜露天电影(Summer Night Open-Air Movie),spotify:track:2HqbxDaTBfMU3X1oraaKll,trackdone,trackdone,True,False,False,1.765174e+09,False,2025,December,Monday,6,Mobile
39565,2025-12-08 06:19:13+00:00,android,208307,Paparazzi,Lady Gaga,The Fame,spotify:track:02XnQdf7sipaKBBHixz3Zp,trackdone,trackdone,True,False,False,1.765175e+09,False,2025,December,Monday,6,Mobile
39566,2025-12-08 06:22:37+00:00,android,203352,Burning Up (Fire),BTS,The Most Beautiful Moment in Life: Young Forever,spotify:track:0aE3V0zgSD2YwkEHW42gxG,trackdone,trackdone,True,False,False,1.765175e+09,False,2025,December,Monday,6,Mobile
39567,2025-12-08 06:28:30+00:00,android,353253,Enchanted (Taylor's Version),Taylor Swift,Speak Now (Taylor's Version),spotify:track:3sW3oSbzsfecv9XoUdGs7h,trackdone,trackdone,True,False,False,1.765175e+09,False,2025,December,Monday,6,Mobile

In [22]:
df['listening_minutes'] = df['ms_played'] / 60000

In [23]:
def get_day_part(hour):
    if 5 <= hour < 12: return 'Morning'
    elif 12 <= hour < 17: return 'Afternoon'
    elif 17 <= hour < 21: return 'Evening'
    else: return 'Night'

df['day_part'] = df['hour'].apply(get_day_part)

In [24]:
def get_season(month):
    if month in ['December', 'January', 'February']: return 'Winter'
    elif month in ['March', 'April', 'May']: return 'Spring'
    elif month in ['June', 'July', 'August']: return 'Summer'
    else: return 'Autumn'

df['season'] = df['month'].apply(get_season)

In [25]:
df['is_weekend'] = df['day_of_week'].isin(['Saturday', 'Sunday'])

In [26]:
df.to_csv('spotify_cleaned.csv', index=False)

In [27]:
df.nunique()

ts                   35568
platform                 8
ms_played            10292
track                 5228
artist                1903
album                 3878
spotify_track_uri     6008
start_reason             9
end_reason               9
shuffle                  2
skipped                  2
offline                  2
offline_timestamp    31983
incognito_mode           1
year                     4
month                   12
day_of_week              7
hour                    24
device_type              4
listening_minutes    10292
day_part                 4
season                   4
is_weekend               2
dtype: int64

In [28]:
pip install pyodbc sqlalchemy

Requirement already satisfied: pyodbc in c:\users\miree\anaconda3\lib\site-packages (5.2.0)
Requirement already satisfied: sqlalchemy in c:\users\miree\anaconda3\lib\site-packages (2.0.39)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\miree\anaconda3\lib\site-packages (from sqlalchemy) (3.1.1)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\miree\anaconda3\lib\site-packages (from sqlalchemy) (4.12.2)
Note: you may need to restart the kernel to use updated packages.

In [29]:
import urllib
from sqlalchemy import create_engine,types
import pandas as pd

df = df.rename(columns={'ts': 'event_time'})
odbc_str = (
    "Driver={ODBC Driver 18 for SQL Server};"
    "server=Mireesh-HP;"
    "Database=spotify_analysis;"
    "Trusted_Connection=yes;"
    "TrustServerCertificate=yes;"
)


dtype_map = {
    'event_time': types.DateTime(),
    'track': types.NVARCHAR('max'),
    'artist': types.NVARCHAR('max'),
    'album': types.NVARCHAR('max'),
    'platform': types.NVARCHAR('max'),
    'end_reason': types.NVARCHAR(50),
    'start_reason': types.NVARCHAR(50)
}

params = urllib.parse.quote_plus(odbc_str)
engine = create_engine("mssql+pyodbc:///?odbc_connect=%s" % params)


database_name = "spotify_analysis" 

table_name = "spotify"

df.to_sql(table_name, engine, if_exists="replace", index=False,dtype = dtype_map, chunksize=1000)
print(f"Data successfully loaded into table '{table_name}' in database '{database_name}'.")

Data successfully loaded into table 'spotify' in database 'spotify_analysis'.

In [30]:
pip install spotipy

Requirement already satisfied: spotipy in c:\users\miree\anaconda3\lib\site-packages (2.25.2)
Requirement already satisfied: redis>=3.5.3 in c:\users\miree\anaconda3\lib\site-packages (from spotipy) (7.1.0)
Requirement already satisfied: requests>=2.25.0 in c:\users\miree\anaconda3\lib\site-packages (from spotipy) (2.32.3)
Requirement already satisfied: urllib3>=1.26.0 in c:\users\miree\anaconda3\lib\site-packages (from spotipy) (2.3.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\miree\anaconda3\lib\site-packages (from requests>=2.25.0->spotipy) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\miree\anaconda3\lib\site-packages (from requests>=2.25.0->spotipy) (3.7)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\miree\anaconda3\lib\site-packages (from requests>=2.25.0->spotipy) (2025.11.12)
Note: you may need to restart the kernel to use updated packages.

In [33]:
import pandas as pd
import spotipy
from spotipy.oauth2 import SpotifyClientCredentials
from spotipy.cache_handler import MemoryCacheHandler
import time

auth_manager = SpotifyClientCredentials(
    client_id='7e52b06ac74e4b6dac0174014aa33aac',
    client_secret='327af686cb384f859db749e24bcb34cf',
    cache_handler=MemoryCacheHandler() 
)
sp = spotipy.Spotify(auth_manager=auth_manager)

top_tracks = df[['track', 'artist']].value_counts().head(5602).index

track_metadata = []
print(f"Fetching Album Covers for top {len(top_tracks)} tracks...")

for i, (track_name, artist_name) in enumerate(top_tracks):
    try:
     
        query = f"track:{track_name} artist:{artist_name}"
        results = sp.search(q=query, type='track', limit=1)
        items = results['tracks']['items']
        
        if items:
            track = items[0]
            track_metadata.append({
                'track': track_name,
                'artist': artist_name,
                'album_cover': track['album']['images'][0]['url'] if track['album']['images'] else None,
                'album_name': track['album']['name']
            })
        
        if (i + 1) % 100 == 0:
            print(f"Processed {i + 1} tracks...")
        time.sleep(0.1)
    except Exception as e:
        continue


df_track_info = pd.DataFrame(track_metadata)
df_track_info.to_sql('track_metadata', con=engine, if_exists='replace', index=False)

print("--- SUCCESS: Track Album Covers are now in SQL! ---")

Fetching Album Covers for top 5602 tracks...
Processed 100 tracks...
Processed 200 tracks...
Processed 300 tracks...
Processed 400 tracks...
Processed 500 tracks...
Processed 600 tracks...
Processed 700 tracks...
Processed 800 tracks...
Processed 900 tracks...
Processed 1000 tracks...
Processed 1100 tracks...
Processed 1200 tracks...
Processed 1300 tracks...
Processed 1400 tracks...
Processed 1500 tracks...
Processed 1600 tracks...
Processed 1700 tracks...
Processed 1800 tracks...
Processed 1900 tracks...
Processed 2000 tracks...
Processed 2100 tracks...
Processed 2200 tracks...
Processed 2300 tracks...
Processed 2400 tracks...
Processed 2500 tracks...
Processed 2600 tracks...
Processed 2700 tracks...
Processed 2800 tracks...
Processed 2900 tracks...
Processed 3000 tracks...
Processed 3100 tracks...
Processed 3200 tracks...
Processed 3300 tracks...
Processed 3400 tracks...
Processed 3500 tracks...
Processed 3600 tracks...
Processed 3700 tracks...
Processed 3800 tracks...
Processed 3900 tracks...
Processed 4000 tracks...
Processed 4100 tracks...
Processed 4200 tracks...
Processed 4300 tracks...
Processed 4400 tracks...
Processed 4500 tracks...
Processed 4600 tracks...
Processed 4700 tracks...
Processed 4800 tracks...
Processed 4900 tracks...
Processed 5000 tracks...
Processed 5100 tracks...
Processed 5200 tracks...
Processed 5300 tracks...
Processed 5400 tracks...
Processed 5500 tracks...
Processed 5600 tracks...
--- SUCCESS: Track Album Covers are now in SQL! ---